import Link from 'next/link';
import { addressSchema } from '@/lib/trading/shared';
import { tokenContext } from '@/lib/intelligence/token-context';
import { IntelligenceHeader, knownUsd, knownPercent, Coverage } from '@/components/intelligence/primitives';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Compare tokens' };
export default async function ComparePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const sp = await searchParams; const raw = typeof sp.tokens === 'string' ? sp.tokens.slice(0, 200) : '';
  const addresses = [...new Set(raw.split(',').map(a => addressSchema.safeParse(a.trim())).filter(a => a.success).map(a => a.data!))].slice(0, 4);
  const contexts = await Promise.all(addresses.map(a => tokenContext(a)));
  const rows = contexts.filter(c => c != null);
  const fields = [['On-chain market cap', (c: NonNullable<typeof contexts[number]>) => knownUsd(c.marketCap)], ['Liquidity', c => knownUsd(c.liquidity)], ['Volume · 24h', c => knownUsd(c.volume24h)], ['Price change · 1h', c => knownPercent(c.inputs.priceChange1h)], ['Recorded unique buyers · 1h', c => String(c.inputs.buyersCurrent)], ['Qualified buyers', c => String(c.consensus.highBuyers)], ['Smart-money net · 1h', c => knownUsd(c.consensus.smartMoneyNet)], ['Runner score', c => c.runner.score == null ? 'Not rated' : `${c.runner.score}/100`], ['Input coverage', c => knownPercent(c.runner.coverage * 100)], ['Risk', c => c.risk.level]] as [string, (c: NonNullable<typeof contexts[number]>) => string][];
  return <><IntelligenceHeader title="Compare tokens" description="Compare up to four Robinhood tokens using the same measured fields and visible source coverage." /><form className="mb-6 flex flex-col gap-3 sm:flex-row"><label className="min-w-0 flex-1 text-sm text-secondary">Token contract addresses, separated by commas<input name="tokens" defaultValue={raw} maxLength={200} placeholder="0x… , 0x…" className="mt-2 block w-full rounded-lg border border-border bg-surface p-3 text-base" /></label><button className="self-start rounded-full bg-neon px-5 py-3 text-sm text-black sm:self-end">Compare</button></form>{raw && addresses.length !== raw.split(',').filter(a => a.trim()).length && <p className="mb-4 text-sm text-warning">Use up to four distinct, valid contract addresses.</p>}{contexts.some(c => !c) && <p className="mb-4 text-sm text-warning">Some tokens are not yet present in the monitored database.</p>}{rows.length > 0 ? <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-left text-sm"><caption className="sr-only">Token comparison</caption><thead><tr><th className="p-4 text-muted">Metric</th>{rows.map(c => <th className="p-4" key={c.token.address}><Link href={`/token/${c.token.address}`} className="text-neon">${c.token.symbol}</Link></th>)}</tr></thead><tbody>{fields.map(([name, render]) => <tr key={name} className="border-t border-border"><th className="whitespace-nowrap p-4 font-normal text-secondary">{name}</th>{rows.map(c => <td key={c.token.address} className="whitespace-nowrap p-4 tnum">{render(c)}</td>)}</tr>)}<tr className="border-t border-border"><th className="p-4 font-normal text-secondary">Market observed</th>{rows.map(c => <td key={c.token.address} className="p-4 text-xs text-muted">{new Date(c.observedAt).toLocaleString()}</td>)}</tr></tbody></table></div> : <p className="rounded-lg border border-border p-5 text-sm text-muted">Add contract addresses to compare observed market data.</p>}<Coverage>Market provider snapshots and Analyst-computed monitored trades. Missing data is not ranked as zero. Smart-money quality requires sufficient internally measured history. Market snapshots can have different observation times.</Coverage></>;
}
