import Link from 'next/link';
import { listTokens, getToken } from '@/lib/services/intelligence';
import { TokenAvatar } from '@/components/common/avatar';
import { TokenResearch } from '@/components/tokens/token-research';
import { formatPrice } from '@/lib/format';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Why is it pumping?' };
export default async function ResearchPage({ searchParams }: { searchParams: Promise<{ token?: string; q?: string }> }) {
  const sp = await searchParams;
  const tokens = await listTokens({ tab: 'traded', window: '24h', limit: 24, query: sp.q?.slice(0,80) });
  const selected = /^0x[\da-f]{40}$/i.test(sp.token ?? '') ? await getToken(sp.token!.toLowerCase()) : tokens[0];
  return <div className="space-y-7"><header className="max-w-2xl"><p className="mb-3 text-xs font-medium text-neon">MARKET RESEARCH</p><h1 className="text-3xl font-medium tracking-tight sm:text-4xl">Why is it pumping?</h1><p className="mt-3 text-sm leading-relaxed text-secondary">Trace a move through real trades, wallet activity and market data. Choose a token to examine the evidence.</p></header>
    <div className="grid items-start gap-5 lg:grid-cols-[280px_minmax(0,1fr)]"><aside className="rounded-xl border border-border bg-surface"><form action="/radar" className="flex gap-2 border-b border-border p-3"><input aria-label="Find a token to research" name="q" defaultValue={sp.q} placeholder="Symbol or address" className="min-w-0 flex-1 bg-transparent px-1 text-sm outline-none"/><button className="rounded-lg border border-border px-3 py-2 text-xs hover:text-neon">Find</button></form><div className="max-h-[520px] overflow-y-auto">{tokens.map(t => <Link key={t.address} href={`/radar?token=${t.address}`} aria-current={selected?.address === t.address ? 'true' : undefined} className={`flex items-center gap-3 border-b border-border/50 p-3 transition-colors hover:bg-hover ${selected?.address === t.address ? 'bg-neon/5' : ''}`}><TokenAvatar address={t.address} symbol={t.symbol} image={t.image} size="sm"/><span className="min-w-0 flex-1 truncate text-sm font-medium">{t.symbol}</span><span className="text-xs text-secondary tnum">{formatPrice(t.price)}</span></Link>)}{!tokens.length && <p className="p-5 text-sm text-muted">No matching tokens. Try another symbol or address.</p>}</div></aside>
    <section className="min-w-0 space-y-4" aria-label="Token research workspace">{selected ? <><div className="flex flex-wrap items-center gap-3 rounded-xl border border-border p-5"><TokenAvatar address={selected.address} symbol={selected.symbol} image={selected.image}/><div className="min-w-0 flex-1"><h2 className="text-xl font-medium">{selected.name}</h2><p className="mt-1 text-xs text-muted">{selected.symbol} · Robinhood Chain</p></div><span className="text-xl tnum">{formatPrice(selected.price)}</span><Link href={`/token/${selected.address}`} className="rounded-full border border-border px-4 py-2 text-xs hover:text-neon">Open chart ↗</Link></div><TokenResearch key={selected.address} address={selected.address}/><p className="px-1 text-xs leading-relaxed text-muted">Analysis distinguishes measured activity from possible explanations. Missing history and unverified catalysts remain explicit.</p></> : <p className="p-8 text-sm text-muted">Choose a token with available market data.</p>}</section></div></div>;
}
