import Link from 'next/link';
import { positionsForWallet } from '@/lib/intelligence/positions';
import { addressSchema } from '@/lib/trading/shared';
import { IntelligenceHeader, EvidenceMetric, Coverage, knownUsd } from '@/components/intelligence/primitives';
import { EmptyState } from '@/components/ui/states';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Positions' };
export default async function PositionsPage({ searchParams }: { searchParams: Promise<{ wallet?: string }> }) {
  const sp = await searchParams, parsed = addressSchema.safeParse(sp.wallet);
  const positions = parsed.success ? await positionsForWallet(parsed.data) : [];
  return <><IntelligenceHeader title="Positions & entry thesis" description="Confirmed in-app acquisitions with their original entry evidence. Wallet token balances are shown separately from individual entry amounts." /><form className="mb-6 flex flex-col gap-3 sm:flex-row"><label className="min-w-0 flex-1 text-sm text-secondary">Public wallet address<input name="wallet" defaultValue={sp.wallet ?? ''} maxLength={42} placeholder="0x…" className="mt-2 block w-full rounded-lg border border-border bg-surface p-3 text-base" /></label><button className="self-start rounded-full bg-neon px-5 py-3 text-sm text-black sm:self-end">View positions</button></form>{sp.wallet && !parsed.success && <p role="alert" className="mb-4 text-sm text-warning">Enter a valid wallet address.</p>}{positions.length ? <div className="space-y-5">{positions.map(p => <article key={p.id} className="card p-5"><div className="flex flex-wrap justify-between gap-3"><Link className="text-lg font-medium text-neon" href={`/token/${p.token}`}>${p.symbol}</Link><span className="text-xs text-secondary">{p.comparison.status}</span></div><dl className="mt-5 grid grid-cols-2 gap-5 lg:grid-cols-4"><EvidenceMetric label="Acquired in this receipt">{p.amount}</EvidenceMetric><EvidenceMetric label="Entry cost · USD">{knownUsd(p.totalCost)}</EvidenceMetric><EvidenceMetric label="Entire wallet token balance" hint="Includes other entries and transfers; do not sum across entry rows.">{p.currentAmount ?? 'Not measured'}</EvidenceMetric><EvidenceMetric label="Entry market cap">{knownUsd(p.entryMarketCap)}</EvidenceMetric></dl><ul className="mt-4 space-y-2 text-sm text-secondary">{p.comparison.changes.map(c => <li key={c}>{c}</li>)}</ul><a className="mt-4 inline-block text-xs text-neon underline" href={`https://robinhoodchain.blockscout.com/tx/${p.entryTransaction}`} target="_blank" rel="noreferrer">Verified entry transaction</a><Coverage>{p.comparison.coverage}. Acquired {p.openedAt.toLocaleString()} · balance observed {p.updatedAt.toLocaleString()}. Unknown cost basis cannot produce a reliable position PnL.</Coverage></article>)}</div> : <EmptyState title="No verified entries for this wallet yet." description="After an in-app swap confirms, its chain receipt is checked before the position is recorded. Existing wallet holdings are not invented as new purchases." />}</>;
}
