import Link from 'next/link';
import { eq, inArray, desc } from 'drizzle-orm';
import { getDb, schema } from '@/lib/db';
import { getGuest } from '@/lib/social/guest';
import { IntelligenceHeader, Coverage, knownUsd } from '@/components/intelligence/primitives';
import { EmptyState } from '@/components/ui/states';
import { alertInbox, recentFollowedSignals } from '@/lib/intelligence/alerts';
import { listTrades } from '@/lib/services/intelligence';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Your feed' };
export default async function FeedPage() {
  const db = await getDb(), guest = await getGuest();
  const [preferences] = guest ? await db.select().from(schema.userPreferences).where(eq(schema.userPreferences.guestId, guest.id)).limit(1) : [];
  const follows = (preferences?.follows ?? []) as string[], watchlist = (preferences?.watchlist ?? []) as string[];
  const [alerts, signals, trades, reports] = await Promise.all([guest ? alertInbox(guest.id) : [], recentFollowedSignals(watchlist), follows.length ? listTrades({ traderIds: follows, limit: 40 }) : [], watchlist.length ? db.select().from(schema.whyPumpingReports).where(inArray(schema.whyPumpingReports.token, watchlist)).orderBy(desc(schema.whyPumpingReports.generatedAt)).limit(20) : []]);
  return <><IntelligenceHeader title="Your feed" description="Followed traders, saved tokens, research and alert history, tied to your anonymous browser profile." /><div className="mb-5 flex flex-wrap gap-3"><Link className="text-sm text-neon" href="/following">Manage followed traders</Link><Link className="text-sm text-neon" href="/watchlist">Your watchlist</Link><Link className="text-sm text-neon" href="/alerts">Manage alerts</Link></div>{!follows.length && !watchlist.length && <EmptyState title="Make this feed yours." description="Follow a trader or watch a token. New saved choices are stored with this browser profile; no wallet connection is required." />}<div className="grid gap-5 lg:grid-cols-2"><section className="card p-5"><h2 className="text-lg font-medium">Followed trader activity</h2><ul className="mt-4 divide-y divide-border">{trades.map(t => <li key={t.id} className="py-3 text-sm"><Link href={`/trader/${t.traderId}`} className="font-medium">{t.trader.name}</Link> <span className={t.side === 'BUY' ? 'text-neon' : 'text-negative'}>{t.side}</span> <Link href={`/token/${t.token.address}`} className="text-neon">${t.token.symbol}</Link><span className="ms-2 text-secondary">{knownUsd(t.amountUsd)}</span></li>)}</ul>{!trades.length && <Coverage>No recorded activity in this feed yet.</Coverage>}</section><section className="card p-5"><h2 className="text-lg font-medium">Saved-token signals & research</h2><ul className="mt-4 space-y-4">{signals.map(s => <li key={s.id} className="text-sm"><Link className="text-neon" href={`/token/${s.token}`}>{s.signalType} · {s.token.slice(0, 8)} · {s.finalScore}/100</Link><p className="mt-1 text-xs text-muted">{s.timestamp.toLocaleString()}</p></li>)}{reports.map(r => <li key={r.id}><Link className="text-sm text-neon" href={`/token/${r.token}`}>{r.primaryCatalyst}</Link><p className="mt-1 text-xs text-muted">Base44 report · {r.generatedAt.toLocaleString()}</p></li>)}</ul>{!signals.length && !reports.length && <Coverage>No recent signals or reports for your saved tokens.</Coverage>}</section><section className="card p-5 lg:col-span-2"><h2 className="text-lg font-medium">Alert history</h2><ul className="mt-4 space-y-3">{alerts.map(a => { const p = a.payload as { title: string; side: string; count: number; amountUsd: number | null; token: { address: string; symbol: string } }; return <li key={a.id} className="text-sm"><Link href={`/token/${p.token.address}`} className="text-neon">{p.title} · {p.side} ${p.token.symbol}</Link><span className="ms-2 text-secondary">{p.count} fills · {knownUsd(p.amountUsd)}</span><p className="mt-1 text-xs text-muted">{a.createdAt.toLocaleString()}</p></li>; })}</ul>{!alerts.length && <Coverage>No server alerts delivered yet. The worker evaluates enabled rules and groups completed one-minute trade intervals. Live in-tab alerts remain immediate.</Coverage>}</section></div></>;
}
