'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { knownUsd, knownPercent, EvidenceMetric, Coverage } from './primitives';
import type { TokenIntelligence } from '@/lib/intelligence/token-context';

import type { assessTokenRisk } from '@/lib/intelligence/risk';
type RiskResult = Awaited<ReturnType<typeof assessTokenRisk>>;
export function TokenIntelligencePanel({ context }: { context: TokenIntelligence }) {
  const [inspect, setInspect] = useState(false);
  const risk = useQuery<RiskResult>({ queryKey: ['token-risk', context.token.address], enabled: inspect, staleTime: 300_000, queryFn: async () => { const r = await fetch(`/api/tokens/${context.token.address}/risk`); if (!r.ok) throw new Error('Risk checks could not load.'); return r.json(); } });
  return <section aria-labelledby="token-intelligence-title" className="card p-4 sm:p-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 id="token-intelligence-title" className="text-lg font-medium">Market intelligence</h2><Link href={`/compare?tokens=${context.token.address}`} className="rounded-full border border-border px-3 py-2 text-xs text-secondary hover:text-neon">Compare token</Link></div>
    <dl className="mt-5 grid grid-cols-2 gap-x-5 gap-y-6 md:grid-cols-4"><EvidenceMetric label="Activity score" hint={`${Math.round(context.runner.coverage * 100)}% of inputs measured`}>{context.runner.score ?? 'Not rated'}</EvidenceMetric><EvidenceMetric label="Signal">{context.runner.signalType}</EvidenceMetric><EvidenceMetric label="Qualified buyer wallets" hint="Quality ≥65 · confidence ≥60%">{context.consensus.highBuyers}</EvidenceMetric><EvidenceMetric label="Smart-money net · 1h">{knownUsd(context.consensus.smartMoneyNet)}</EvidenceMetric></dl>
    <details className="mt-5 rounded-lg bg-elevated p-3"><summary className="text-sm text-secondary">Why this score?</summary><ul className="mt-3 space-y-2 text-xs leading-relaxed text-secondary">{context.runner.reasons.map(r => <li key={r}>{r}</li>)}</ul><dl className="mt-3 grid grid-cols-2 gap-3">{context.runner.components.map(c => <EvidenceMetric key={c.key} label={`${c.key} · ${c.weight}% weight`}>{c.value == null ? 'Not measured' : `${Math.round(c.value)}/100`}</EvidenceMetric>)}</dl><Coverage>{context.consensus.methodology}</Coverage></details>
    <Coverage>{context.coverage.source} · {context.coverage.period} · calculated {new Date(context.calculatedAt).toISOString()}. {context.coverage.trades}. A watch signal is an observed pattern, not a prediction.</Coverage>
    <div className="mt-6 flex flex-wrap gap-3"><Button onClick={() => setInspect(true)} disabled={risk.isFetching}>{risk.isFetching ? 'Checking evidence…' : 'Inspect risks & holders'}</Button></div>
    {inspect && <div className="mt-5 border-t border-border pt-5"><h3 className="font-medium">Risk evidence</h3>{risk.error && <p role="alert" className="mt-2 text-sm text-warning">{risk.error.message}</p>}{risk.data?.data ? <><dl className="mt-4 grid grid-cols-2 gap-5"><EvidenceMetric label="Assessment">{risk.data.data.level}</EvidenceMetric><EvidenceMetric label="Check coverage">{Math.round(risk.data.data.coverage * 100)}%</EvidenceMetric><EvidenceMetric label="Top 10 sampled holders">{knownPercent(risk.data.data.holders.top10)}</EvidenceMetric><EvidenceMetric label="Creator holdings">{knownPercent(risk.data.data.evidence.creatorPercent)}</EvidenceMetric><EvidenceMetric label="Mint capability">{risk.data.data.evidence.mint}</EvidenceMetric><EvidenceMetric label="Sell simulation">{risk.data.data.evidence.sellSimulation}</EvidenceMetric></dl><ul className="mt-4 space-y-2 text-sm text-warning">{risk.data.data.flags.map(f => <li key={f}>{f}</li>)}</ul><details className="mt-4"><summary className="text-sm text-secondary">Holder accounts & limitations</summary><ol className="mt-3 space-y-2">{risk.data.data.holders.holders.map(h => <li key={h.address} className="flex flex-wrap justify-between gap-2 text-xs"><Link className="break-all text-secondary hover:text-neon" href={`/wallet/${h.address}`}>{h.address}</Link><span>{h.percent.toFixed(2)}%</span></li>)}</ol>{risk.data.data.limitations.map(l => <Coverage key={l}>{l}</Coverage>)}</details><Coverage>{risk.data.stale ? 'Stale evidence · ' : ''}{risk.data.data.provenance.source} · {risk.data.data.provenance.calculatedAt}</Coverage></> : risk.data && <p className="mt-2 text-sm text-muted">Evidence {risk.data.status}. No safe rating has been assigned.</p>}</div>}
  </section>;
}
