"use client";
import Link from "next/link";
import { useState } from "react";
import { alertRuleSchema, type AlertRule, type TrackingState } from "@/lib/client/tracking-model";
import { updateTracking, useTracking } from "@/lib/client/tracking-store";
import { toast } from "@/lib/client/toast";
import { formatUsd } from "@/lib/format";
const blank = (): AlertRule => ({ id: "", name: "", scope: "following", wallet: "", side: "all", minUsd: 0, token: "", enabled: true, armedAt: 0 });
const field = "mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-primary";
function save(change: (s: TrackingState) => TrackingState) { const ok = updateTracking(change); if (!ok) toast("Allow browser storage to save alerts.", "negative"); return ok; }
export function Alerts() {
  const state = useTracking();
  const [draft, setDraft] = useState<AlertRule>(blank);
  const [error, setError] = useState("");
  return <div className="space-y-6"><p className="text-sm leading-relaxed text-secondary">Rules and the latest 100 alerts stay on this device. Alerts run while ANALYST is open, for trades received from our sources. Historical imports do not trigger alerts.</p>
    <form className="card space-y-4 p-5" onSubmit={e => { e.preventDefault(); const parsed = alertRuleSchema.safeParse({ ...draft, id: draft.id || crypto.randomUUID(), armedAt: Date.now() }); if (!parsed.success) { setError("Enter a rule name, valid wallet if selected, and a non-negative USD amount."); return; } if (!draft.id && state.rules.length >= 30) { setError("You can save up to 30 rules."); return; } if (save(s => ({ ...s, rules: [...s.rules.filter(r => r.id !== parsed.data.id), parsed.data] }))) { setDraft(blank()); setError(""); toast("Alert rule saved", "positive"); } }}>
      <h2 className="text-lg">{draft.id ? "Edit alert" : "Create alert"}</h2>
      <div className="grid gap-4 sm:grid-cols-2"><label className="text-xs text-secondary">Rule name<input required maxLength={80} className={field} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="Large buys from my traders" /></label>
      <label className="text-xs text-secondary">Traders<select aria-label="Traders" className={field} value={draft.scope} onChange={e => setDraft({ ...draft, scope: e.target.value as AlertRule["scope"] })}><option value="following">Followed traders</option><option value="all">All covered traders</option><option value="wallet">Specific wallet</option></select></label>
      {draft.scope === "wallet" && <label className="text-xs text-secondary sm:col-span-2">Wallet address<input required className={field} value={draft.wallet} onChange={e => setDraft({ ...draft, wallet: e.target.value.trim() })} placeholder="0x…" /></label>}
      <label className="text-xs text-secondary">Action<select aria-label="Action" className={field} value={draft.side} onChange={e => setDraft({ ...draft, side: e.target.value as AlertRule["side"] })}><option value="all">Buys and sells</option><option value="BUY">Buys</option><option value="SELL">Sells</option></select></label>
      <label className="text-xs text-secondary">Minimum trade value (USD)<input className={field} type="number" min="0" max="1000000000000" step="any" required value={draft.minUsd} onChange={e => setDraft({ ...draft, minUsd: Number(e.target.value) })} /></label>
      <label className="text-xs text-secondary sm:col-span-2">Token symbol or address (optional)<input className={field} maxLength={64} value={draft.token} onChange={e => setDraft({ ...draft, token: e.target.value })} placeholder="Any token" /></label></div>
      {draft.scope === "following" && !state.following.length && <p className="text-xs text-warning">Follow a trader first for this rule to match trades.</p>}{error && <p role="alert" className="text-negative text-sm">{error}</p>}
      <div className="flex gap-4"><button className="rounded-lg bg-neon px-4 py-2 text-sm font-medium text-background">Save alert</button>{draft.id && <button type="button" onClick={() => setDraft(blank())}>Cancel edit</button>}</div>
    </form>
    <section className="space-y-3"><h2 className="text-lg">Rules · {state.rules.length}</h2>{!state.rules.length && <p className="text-sm text-muted">No rules yet.</p>}{state.rules.map(r => <div className="card flex flex-wrap items-center justify-between gap-3 p-4" key={r.id}><div className="min-w-0"><p className="break-words font-medium">{r.name}</p><p className="mt-1 break-all text-xs text-muted">{r.scope === "following" ? "Following" : r.scope === "wallet" ? r.wallet : "All covered traders"} · {r.side} · ≥ {formatUsd(r.minUsd)} · {r.token || "Any token"}</p></div><div className="flex gap-4 text-xs"><button aria-label={`${r.enabled ? "Pause" : "Enable"} ${r.name}`} className={r.enabled ? "text-neon" : "text-muted"} onClick={() => save(s => ({ ...s, rules: s.rules.map(v => v.id === r.id ? { ...v, enabled: !v.enabled, armedAt: Date.now() } : v) }))}>{r.enabled ? "Active" : "Paused"}</button><button onClick={() => setDraft(r)}>Edit</button><button className="text-negative" aria-label={`Delete ${r.name}`} onClick={() => save(s => ({ ...s, rules: s.rules.filter(v => v.id !== r.id) }))}>Delete</button></div></div>)}</section>
    <button className="rounded-lg border border-border px-4 py-2 text-sm" onClick={async () => { if (state.desktop) { save(s => ({ ...s, desktop: false })); return; } if (!("Notification" in window)) { toast("This browser does not support desktop notifications."); return; } const permission = await Notification.requestPermission(); if (permission === "granted") save(s => ({ ...s, desktop: true })); else toast("Notifications are blocked. You can still use the alert inbox."); }}>{state.desktop ? "Turn off browser notifications" : "Enable browser notifications"}</button>
    <section className="space-y-3"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg">Alert inbox</h2><div className="flex gap-4 text-xs"><button onClick={() => save(s => ({ ...s, inbox: s.inbox.map(a => ({ ...a, read: true })) }))}>Mark all read</button><button onClick={() => save(s => ({ ...s, inbox: [] }))}>Clear inbox</button></div></div>{!state.inbox.length && <p className="card p-6 text-sm text-secondary">New matching trades will appear here.</p>}{state.inbox.map(a => <article key={a.id} className={`card p-4 ${!a.read ? "border-neon/30" : ""}`}><p className="text-sm"><Link className="font-medium hover:text-neon" href={`/trader/${a.trader.id}`}>{a.trader.name}</Link> <span className={a.side === "BUY" ? "text-neon" : "text-negative"}>{a.side === "BUY" ? "bought" : "sold"}</span> {formatUsd(a.amountUsd)} of <Link className="text-neon" href={`/token/${a.token}`}>{a.symbol}</Link></p><p className="mt-2 text-xs text-muted">{new Date(a.timestamp).toLocaleString()} · {a.ruleNames.join(", ")}</p></article>)}</section>
  </div>;
}
