"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { apiGet } from "@/lib/client/fetcher";
import { formatPrice, formatUsd } from "@/lib/format";
import type { TokenPerformance } from "@/lib/performance";
const duration = (ms: number | null) => ms == null ? "Uncovered" : ms < 60_000 ? "< 1 min" : ms < 3_600_000 ? `${Math.round(ms / 60_000)} min` : ms < 86_400_000 ? `${(ms / 3_600_000).toFixed(1)} hr` : `${(ms / 86_400_000).toFixed(1)} days`;
export function Performance({ wallet }: { wallet: string }) {
  const query = useQuery({ queryKey: ["performance", wallet], queryFn: ({ signal }) => apiGet<{ positions: TokenPerformance[] }>(`/api/traders/${wallet}/performance`, signal), refetchInterval: 30_000 });
  return <section className="card min-w-0 overflow-hidden"><div className="p-5"><h2 className="text-lg font-medium">Entry, exit & holding time</h2><p className="mt-2 max-w-3xl text-xs leading-relaxed text-secondary">Calculated from recorded swaps. Entry and exit are quantity-weighted USD prices. Holding time covers sells matched to recorded buys, weighted by their USD cost. Transfers, fees and unrecorded history are excluded.</p></div>
    {query.isLoading ? <p className="p-5" role="status">Analyzing recorded trades…</p> : query.isError ? <button className="p-5 text-warning" onClick={() => void query.refetch()}>Performance could not load. Retry</button> : !query.data?.positions.length ? <p className="p-5 text-secondary">No recorded swaps to analyze yet.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-right text-xs"><thead className="border-y border-border text-muted"><tr>{["Token", "Avg entry", "Avg exit", "Avg hold (sold)", "Recorded open qty", "Matched PnL", "Coverage"].map(h => <th className="px-4 py-3 font-normal" key={h}>{h}</th>)}</tr></thead><tbody>{query.data.positions.map(p => <tr key={p.address} className="border-b border-border last:border-0"><td className="px-4 py-3"><Link className="font-medium text-neon" href={`/token/${p.address}`}>{p.symbol}</Link></td><td className="px-4 py-3 font-mono">{p.averageEntry == null ? "Uncovered" : formatPrice(p.averageEntry)}</td><td className="px-4 py-3 font-mono">{p.averageExit == null ? "Uncovered" : formatPrice(p.averageExit)}</td><td className="px-4 py-3">{duration(p.holdingMs)}</td><td className="px-4 py-3 font-mono">{p.recordedOpenQuantity == null ? "Uncovered" : p.recordedOpenQuantity.toLocaleString(undefined, { maximumSignificantDigits: 6 })}</td><td className={`px-4 py-3 font-mono ${(p.realizedPnl ?? 0) >= 0 ? "text-neon" : "text-negative"}`}>{p.realizedPnl == null ? "Uncovered" : formatUsd(p.realizedPnl)}</td><td className="px-4 py-3 text-muted">{p.priced}/{p.trades} priced<br />{p.matchedSells} matched sells{p.uncoveredSells > 0 && <span className="block text-warning">{p.uncoveredSells} with uncovered quantity</span>}</td></tr>)}</tbody></table></div>}
    <p className="p-5 text-[11px] leading-relaxed text-muted">Recorded open quantity is an inference from this history, not a wallet balance. “Uncovered” means the required buy, sell or quantity data is missing. Matched PnL covers only the sell quantity with a known cost basis.</p></section>;
}
