import Link from 'next/link';
import { signalPerformance } from '@/lib/intelligence/signal-store';
import { IntelligenceHeader, Coverage, EvidenceMetric, knownPercent } from '@/components/intelligence/primitives';
import { EmptyState } from '@/components/ui/states';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Signal performance' };
export default async function SignalsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const sp = await searchParams; const days = ['7', '30', '90'].includes(String(sp.days)) ? Number(sp.days) : 30;
  const score = Math.min(100, Math.max(0, Number(sp.score) || 0));
  const rows = await signalPerformance(days, score);
  const complete = rows.filter(r => (r.outcome?.coverage as { horizons?: ({ complete?: boolean } | null)[] } | undefined)?.horizons?.[2]?.complete && r.outcome?.return1h != null);
  return <><IntelligenceHeader title="Signal performance" description="Results measured after each original signal. Missing history stays unmeasured; incomplete price coverage is excluded from summary hit rates." /><form className="mb-5 flex flex-wrap items-end gap-4"><label className="text-sm text-secondary">Window<select name="days" defaultValue={days} className="ms-2 rounded border border-border bg-surface p-2">{[7, 30, 90].map(d => <option key={d} value={d}>{d} days</option>)}</select></label><label className="text-sm text-secondary">Minimum score<input name="score" type="number" min="0" max="100" defaultValue={score} className="ms-2 w-20 rounded border border-border bg-surface p-2" /></label><button className="rounded-full bg-neon px-4 py-2 text-sm text-black">Apply filters</button></form><dl className="mb-6 grid grid-cols-2 gap-5 sm:grid-cols-3"><EvidenceMetric label="Stored signals">{rows.length}</EvidenceMetric><EvidenceMetric label="Complete 1h samples">{complete.length}</EvidenceMetric><EvidenceMetric label="Positive return · 1h">{complete.length ? knownPercent(complete.filter(r => r.outcome!.return1h! > 0).length / complete.length * 100) : 'Not measured'}</EvidenceMetric></dl>{rows.length ? <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full text-left text-sm"><caption className="sr-only">Original signals and later observed returns</caption><thead className="bg-surface text-xs text-muted"><tr>{['Token', 'Observed', 'Score', '5m', '15m', '1h', '6h', '24h', 'Max gain 1h', 'Max drawdown 1h', '1h coverage'].map(h => <th key={h} className="whitespace-nowrap p-3 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map(r => <tr key={r.id} className="border-t border-border"><td className="p-3"><Link className="text-neon" href={`/token/${r.token}`}>${r.context.token.symbol}</Link></td><td className="whitespace-nowrap p-3 text-xs text-muted">{new Date(r.timestamp).toLocaleString()}</td><td className="p-3 tnum">{r.finalScore}</td>{[r.outcome?.return5m, r.outcome?.return15m, r.outcome?.return1h, r.outcome?.return6h, r.outcome?.return24h, r.outcome?.maxGain1h, r.outcome?.maxDrawdown1h].map((v, i) => <td key={i} className={`whitespace-nowrap p-3 tnum ${v != null && v > 0 ? 'text-neon' : v != null && v < 0 ? 'text-negative' : 'text-muted'}`}>{knownPercent(v)}</td>)}<td className="p-3 text-xs text-muted">{complete.some(c => c.id === r.id) ? 'Complete samples' : 'Incomplete / pending'}</td></tr>)}</tbody></table></div> : <EmptyState title="No signal outcomes yet." description="The worker stores qualifying signals first, then measures 5m, 15m, 1h, 6h and 24h returns as real observations arrive." />}<Coverage>Maximum 2,000 recent signals shown. Returns use the first observed price within 90 seconds after each horizon. Complete coverage requires no sampling gap over two minutes. Fees, slippage and trade execution are excluded. Results describe this monitored sample, not expected returns.</Coverage></>;
}
